development:
  adapter: mysql2
  database: spiewnik_ror_development
  pool: 5
  timeout: 5000
  username: spiewnik_ror
  password: Test123!@
  hostname: 192.168.1.101

test:
  adapter: mysql2
  database: spiewnik_ror_test
  pool: 5
  timeout: 5000
  username: spiewnik_ror
  password: Test123!@
  hostname: 192.168.1.101

production:
  adapter: mysql2
  database: spiewnik_ror_development
  pool: 5
  timeout: 5000
  username: spiewnik_ror
  password: Test123!@
  hostname: 192.168.1.101
